version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fhir-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - fhir-net

  fhir-server:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
    environment:
      # URL del servidor de autorización Keycloak
      HAPI_FHIR_SECURITY_OAUTH2_AUTH: "http://keycloak:8080/realms/fhir-realm/protocol/openid-connect/auth"
      HAPI_FHIR_SECURITY_OAUTH2_TOKEN: "http://keycloak:8080/realms/fhir-realm/protocol/openid-connect/token"
      HAPI_FHIR_SECURITY_OAUTH2_CLIENT_ID: "fhir-client"
      HAPI_FHIR_SECURITY_OAUTH2_CLIENT_SECRET: "fhir-secret"
    depends_on:
      - keycloak
    networks:
      - fhir-net

volumes:
  postgres_data:

networks:
  fhir-net:
    driver: bridge
